### ISSUE TITLE
few errors

### ISSUE THREAD

**Issue by Rishavamlabs** [markjay4k/3D-Pose-Estimation#4]
Hey Mark,

Can you please help me with below errors:
Warning (from warnings module):
  File "C:\Users\sourav\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py", line 36
    from ._conv import register_converters as _register_converters
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
Traceback (most recent call last):
  File "C:\Users\sourav\Desktop\tf-pose\tf-pose-estimation-master\src\ptrishav.py", line 115, in <module>
    t = Terrain()
  File "C:\Users\sourav\Desktop\tf-pose\tf-pose-estimation-master\src\ptrishav.py", line 45, in __init__
    w, h = model_wh(model)
  File "C:\Users\sourav\Desktop\tf-pose\tf-pose-estimation-master\src\networks.py", line 84, in model_wh
    width, height = map(int, resolution_str.split('x'))
ValueError: invalid literal for int() with base 10: 'mobilenet_thin_432'

**Comment by Oigile** [comment]
Hi,

I've had the same problem and what worked for me is changing the following:
- model = 'mobilenet_thin' instead of: model = 'mobilenet_thin_432x368'
- w, h= model_wh('432x368') instead of w, h = model_wh(model)
The problem might be caused by updates by idoolnet to his repo, but I am not sure about this. 
Also, I have a problem with reading the prob_model_params.mat now.

Note that I am very new to all this, but I hope this works for you as well!

**Comment by Rishavamlabs** [comment]
Thanks Oigile, i discovered same issue with prob_model_params.mat

**Comment by markjay4k** [comment]
looks like its not loading the correct model. could be a typo.

**Comment by intissarkh** [comment]
can you help me please i run pt3-runwebcam3D.py but there is a problem idont find this file models in the file lifting where there is propmodel:
Traceback (most recent call last):
  File "/home/intissar/montravail/tf-openpose/src/pt3-webcam3D", line 119, in <module>
    t = Terrain()
  File "/home/intissar/montravail/tf-openpose/src/pt3-webcam3D", line 53, in __init__
    self.poseLifting = Prob3dPose('lifting/models/prob_model_params.mat')
  File "/home/intissar/montravail/tf-openpose/src/lifting/prob_model.py", line 19, in __init__
    model_param = sio.loadmat(prob_model_path)
  File "/home/intissar/PycharmProjects/untitled/venv/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/intissar/PycharmProjects/untitled/venv/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/home/intissar/PycharmProjects/untitled/venv/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: 'lifting/models/prob_model_params.mat'

**Comment by CompliceU** [comment]
Traceback (most recent call last):
  File "src/webcam3d.py", line 118, in <module>
    t = Terrain()
  File "src/webcam3d.py", line 54, in __init__
    keypoints = self.mesh(image)
  File "src/webcam3d.py", line 81, in mesh
    transformed_pose2d, weights = self.poseLifting.transform_joints(pose_2d_mpiis, visibilities)
  File "/home/puppy/3d-pose/tf-pose/src/lifting/prob_model.py", line 140, in transform_joints
    assert (pose_2d.ndim == 3)
AssertionError
@markjay4k @Oigile i met this problem ,do you know how to solve it?

**Comment by chener2** [comment]
I've encountered the error message ValueError: invalid literal for int() with base 10: 'mobilenet_thin_432'. This is variable 'model' has been split wrongly. my solution is to modify the below codes.

After debugging I found that the model_name passed into the resolution_str has been split wrongly with delimiter 'x' from 'mobilenet_thin_432x368' to mobilenet__thin_432. I modified the code for model_wh in networks.py to extract the width and height correctly. The code modified is marked >>, you can remove the >> in the actual code..

in py4-webcam3D.py
        w, h = model_wh(model)
>.>   model_n_wh = model[7:]
>>  model = model[:len(model)-8]
   
in networks.py #located in 'tf_pose_estimation\tf_pose'
def model_wh(resolution_str):
>>    mod = resolution_str.rsplit('_')
 >>   width, height = map(int, mod[2].split('x'))
    if width % 16 != 0 or height % 16 != 0:
        raise Exception('Width and height should be multiples of 16. w=%d, h=%d' % (width, height))
    return int(width), int(height)
